apps/about/urls.py
from django.urls import path
from about import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

apps/api/urls.py
from django.urls import path, include
from api import views
from rest_framework import routers


app_name = 'api'

router_v1 = routers.SimpleRouter()
router_v1.register('favorites', views.FavoriteViewSet, basename='favorites')
router_v1.register('subscriptions', views.SubscribeViewSet,
                   basename='subscriptions')
router_v1.register('ingredients', views.IngredientViewSet,
                   basename='ingredients')
router_v1.register('purchases', views.PurchaseViewSet, basename='purchases')


urlpatterns = [
    path('v1/', include(router_v1.urls))
]

apps/recipes/urls.py
from django.urls import path
from recipes import views
from django.views.generic import RedirectView

app_name = 'recipes'

urlpatterns = [
    path('', RedirectView.as_view(url='recipes/')),
    path('recipes/', views.RecipeListView.as_view(), name='index'),
    path('recipes/create/', views.RecipeEditView.as_view(),
         name='new_recipe'),
    path('recipes/<int:id>/<slug:slug>/', views.RecipeDetailView.as_view(),
         name='recipe_details'),
    path('recipes/<int:id>/<slug:slug>/update/',
         views.RecipeEditView.as_view(), name='update_recipe'),
    path('recipes/<int:id>/<slug:slug>/delete/',
         views.RecipeEditView.as_view(), name='delete_recipe'),
    path('profile/<str:username>/', views.ProfileListView.as_view(),
         name='profile'),
    path('favorites/', views.FavoriteListView.as_view(), name='favorites'),
    path('subscribes/', views.SubscribeListView.as_view(), name='subscribes'),
]

apps/shopping_list/urls.py
from django.urls import path
from shopping_list import views


app_name = 'shopping_list'

urlpatterns = [
    path('', views.ShoppingListView.as_view(), name='main'),
    path('download/', views.DownloadShoppingList.as_view(), name='download'),
    path('download/empty', views.EmptyShoppingList.as_view(), name='empty')
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500


admin.site.site_header = "Foodgram Admin"
admin.site.site_title = "Foodgram Admin Panel"
admin.site.index_title = "Welcome to Foodgram"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('about/', include('about.urls', namespace='about')),
    path('shopping_list/', include('shopping_list.urls',
         namespace='shopping_list')),
    path('', include('recipes.urls', namespace='recipes')),
]

handler404 = "recipes.views.page_not_found"  # noqa
handler500 = "recipes.views.server_error"  # noqa

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/elements/customPage.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Регистрация</title>
    <link rel="stylesheet" href="./pages/index.css">
</head>
<body class="body">
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                <li class="nav__item nav__item_disabled"><a href="#" class="nav__link link">Рецепты</a></li>
                <li class="nav__item nav__item_disabled"><a href="#" class="nav__link link">Список покупок</a></li>
            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="#" class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="#" class="button button_style_blue">Создать аккаунт</a></li>
            </ul>
        </div>
    </nav>
</header>
<main class="main container">
    <div class="custom-center-block">
            <p class="custom-text-block">Сообщение пользователю</p>
        <div class="custom-button-block">
            <button class="button button_style_blue">Перейти на главную</button>
        </div>
    </div>


</main>
<footer class="footer">
    <div class="footer__container container">
        <a href="#" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="#" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="#" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>
</body>
</html>

templates/elements/footer.html
    {% load static %}
    <footer class="footer">
        <div class="footer__container container">
            {% now "Y" as current_year %}
            <a href="#" class="footer__brand link">Продуктовый помощник © {{ current_year }}</a>
            <a href="{% url 'recipes:index' %}" class="link" target="_blank"><img src="{% static 'foodgram/img/foodgram_logo.png' %}" height="20px"></a>
            <ul class="footer__items">
                <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе </a></li>
                <li class="footer__item"><a href="{% url 'about:tech'%}" class="footer__link link">Технологии</a></li>
            </ul>
        </div>
    </footer>

templates/elements/nav.html
{% load static %}
{% with request.resolver_match.url_name as url_name %}
    <header class="header">
      <nav class="nav">
          <div class="nav__container container">
              <ul class="nav__items list">
                  <li class="nav__item {% if url_name == 'index' or url_name == 'profile' or url_name == 'recipe_details' %}nav__item_active{% endif %}"><a href="{% url 'recipes:index' %}" class="nav__link link">Рецепты</a></li>
                  {% if user.is_authenticated %}
                  <li class="nav__item {% if url_name == 'subscribes' %}nav__item_active{% endif %}"><a href="{% url 'recipes:subscribes' %}" class="nav__link link">Мои подписки</a></li>
                  <li class="nav__item {% if url_name == 'new_recipe' %}nav__item_active{% endif %}"><a href="{% url 'recipes:new_recipe' %}" class="nav__link link">Создать рецепт</a></li>
                  <li class="nav__item {% if url_name == 'favorites' %}nav__item_active{% endif %}"><a href="{% url 'recipes:favorites' %}" class="nav__link link">Избранное</a></li>
                  {% endif %}
                  <li class="nav__item {% if url_name == 'main' %}nav__item_active{% endif %}"><a href="{% url 'shopping_list:main' %}" class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge" id="counter">{{ shopping_list|length }}</span></li>
              </ul>
              <ul class="nav__items list">
                  <!--
                  <li class="nav__item"><a href="{% url 'recipes:index' %}" class="link" target="_blank"><img src="{% static 'foodgram/img/foodgram_logo.png' %}" height="20px"></a></li>
                  -->
                  {% if user.is_authenticated %}
                  <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
                  <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
                  {% else %}
                  <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                  <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
                  {% endif %}
              </ul>
          </div>
      </nav>
  </header>
  {% endwith %}

templates/elements/paginator.html
        <nav class="pagination" aria-label="Search results pages">
            <ul class="pagination__container">


                {% if page_obj.has_previous %}
                    <li class="pagination__item"><a class="pagination__link link" href="?page=1"><span class="icon-left"></span><span class="icon-left"></span></a></li>
                    <li class="pagination__item"><a class="pagination__link link" href="?page={{ page_obj.previous_page_number }}"><span class="icon-left"></span></a></li>
                {% endif %}

                {% if page_obj.number == page_obj.paginator.num_pages|add:-1 and page_obj.paginator.num_pages >= 5 %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ page_obj.number|add:-3 }}"> {{ page_obj.number|add:-3 }} </a></li>
                {% endif %}
                {% if page_obj.number == page_obj.paginator.num_pages and page_obj.paginator.num_pages >= 5 %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ page_obj.number|add:-3 }}"> {{ page_obj.number|add:-3 }} </a></li>
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ page_obj.number|add:-4 }}"> {{ page_obj.number|add:-4 }} </a></li>
                {% endif %}
                {% if page_obj.number == page_obj.paginator.num_pages and page_obj.paginator.num_pages == 4 %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ page_obj.number|add:-3 }}"> {{ page_obj.number|add:-3 }} </a></li>
                {% endif %}

                {% for i in page_obj.paginator.page_range %}
                    {% if i >= page_obj.number|add:-2 and i <= page_obj.number|add:2 %}
                        <li class="pagination__item {% if i == page_obj.number %} pagination__item_active {% endif %}"><a class="pagination__link link" href="?page={{ i }}"> {{ i }} </a></li>
                    {% endif %}
                {% endfor %}


                {% if page_obj.number == 2 and page_obj.paginator.num_pages >= 5 %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ page_obj.number|add:3 }}"> {{ page_obj.number|add:3 }} </a></li>
                {% endif %}
                {% if page_obj.number == 1 and page_obj.paginator.num_pages >= 5 %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ page_obj.number|add:3 }}"> {{ page_obj.number|add:3 }} </a></li>
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ page_obj.number|add:4 }}"> {{ page_obj.number|add:4 }} </a></li>
                {% endif %}
                {% if page_obj.number == 1 and page_obj.paginator.num_pages == 4 %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ page_obj.number|add:3 }}"> {{ page_obj.number|add:3 }} </a></li>
                {% endif %}


                {% if page_obj.has_next %}
                    <li class="pagination__item"><a class="pagination__link link" href="?page={{ page_obj.next_page_number }}"><span class="icon-right"></span></a></li>
                    <li class="pagination__item"><a class="pagination__link link" href="?page={{ page_obj.paginator.num_pages }}"><span class="icon-right"></span><span class="icon-right"></span></a></li>
                {% endif %}

            </ul>
        </nav>
            <div align="center" style="color:lightgray" class="pagination__link">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                <br>
                Записи с {{ page_obj.start_index }} по {{ page_obj.end_index }} из {{ page_obj.paginator.count }}
            </div>

templates/elements/recipes_list.html
{% load static %}


    <div class="card" data-id="{{ recipe.id }}">
        <a href="{{ recipe.get_absolute_url }}" class="link" target="_blank"><img src="{{ recipe.image.url }}" alt="Какой-то текст" class="card__image"></a>
        <div class="card__body">
            <a class="card__title link" href="{{ recipe.get_absolute_url }}" target="_blank">{{ recipe.title }}</a>
            <ul class="card__items">
                {% if 'обед' in recipe.tags %}
                <li class="card__item"><span class="badge badge_style_green">Обед</span></li>
                {% endif %}
                {% if 'завтрак' in recipe.tags %}
                <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>
                {% endif %}
                {% if 'ужин' in recipe.tags %}
                <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>
                {% endif %}
            </ul>
            <div class="card__items card__items_column">
                <p class="card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>

                <p class="card__text"><span class="icon-user"></span> <a href="{% url 'recipes:profile' recipe.author %}" style="color: black">{% firstof recipe.author.get_full_name recipe.author %}</a></p>

            </div>
        </div>
        <div class="card__footer">
            {% if request.resolver_match.url_name == 'delete_recipe' %}
            {% else %}
            {% if recipe.id in shopping_list %}
            <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span> Рецепт добавлен </button>
            {% else %}
            <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
            {% endif %}
            {% if user.is_authenticated %}
                <button class="button button_style_none" name="favorites" {% if not recipe.is_favorite %}data-out{% endif %}><span class="icon-favorite {% if recipe.is_favorite %}icon-favorite_active{% endif %}"></span></button>
            {% endif %}
            {% endif %}


        </div>
    </div>

templates/elements/tags_filter.html
            <ul class="tags">
                <li class="tags__item">
                    <a id="breakfast" class="tags__checkbox tags__checkbox_style_orange {% if 'breakfast' in filter %}tags__checkbox_active{% endif %}" href="?change_filter=breakfast"></a>
                    <span class="tags__label">Завтрак</span>
                </li>
                <li class="tags__item">
                    <a id="lunch" class="tags__checkbox tags__checkbox_style_green {% if 'lunch' in filter %}tags__checkbox_active{% endif %}" href="?change_filter=lunch"></a>
                    <span for="lunch" class="tags__label">Обед</span>
                </li>
                <li class="tags__item">
                    <a id="dinner" class="tags__checkbox tags__checkbox_style_purple {% if 'dinner' in filter %}tags__checkbox_active{% endif %}" href="?change_filter=dinner"></a>
                    <label for="dinner" class="tags__label">Ужин</label>
                </li>
            </ul>