apps/recipes/urls.py
from django.urls import path
from recipes import views
from django.views.generic import RedirectView

app_name = 'recipes'

urlpatterns = [
    path('', RedirectView.as_view(url='recipes/')),
    path('recipes/', views.RecipeListView.as_view(), name='index'),
    path('recipes/create/', views.RecipeEditView.as_view(),
         name='new_recipe'),
    path('recipes/<int:id>/<slug:slug>/', views.RecipeDetailView.as_view(),
         name='recipe_details'),
    path('recipes/<int:id>/<slug:slug>/update/',
         views.RecipeEditView.as_view(), name='update_recipe'),
    path('recipes/<int:id>/<slug:slug>/delete/',
         views.RecipeEditView.as_view(), name='delete_recipe'),
    path('profile/<str:username>/', views.ProfileListView.as_view(),
         name='profile'),
    path('favorites/', views.FavoriteListView.as_view(), name='favorites'),
    path('subscribes/', views.SubscribeListView.as_view(), name='subscribes'),
]

apps/shopping_list/urls.py
from django.urls import path
from shopping_list import views


app_name = 'shopping_list'

urlpatterns = [
    path('', views.ShoppingListView.as_view(), name='main'),
    path('download/', views.DownloadShoppingList.as_view(), name='download'),
    path('download/empty', views.EmptyShoppingList.as_view(), name='empty')
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500


admin.site.site_header = "Foodgram Admin"
admin.site.site_title = "Foodgram Admin Panel"
admin.site.index_title = "Welcome to Foodgram"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('about/', include('about.urls', namespace='about')),
    path('shopping_list/', include('shopping_list.urls',
         namespace='shopping_list')),
    path('', include('recipes.urls', namespace='recipes')),
]

handler404 = "recipes.views.page_not_found"  # noqa
handler500 = "recipes.views.server_error"  # noqa

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

apps/shopping_list/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Purchase(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                related_name='carts',
                                verbose_name='Пользователь')

    shopping_list = models.JSONField(verbose_name='Список рецептов',
                                     default=list)

    class Meta:
        verbose_name = 'Список покупок'
        verbose_name_plural = 'Списки покупок'

    def __str__(self):
        return f'Список покупок {self.user}'

apps/recipes/forms.py
from django.forms import ModelForm, ValidationError

from recipes.models import Ingredient, IngredientRecipeMap, Recipe


class RecipeForm(ModelForm):

    LOOKUP_NAME = 'nameIngredient'
    LOOKUP_VALUE = 'valueIngredient'

    class Meta:
        model = Recipe
        fields = ('title', 'tags', 'ingredients', 'cooking_time',
                  'description', 'image',)

        error_messages = {
            'title': {'required': '"Название рецепта" обязательное поле'},
            'tags': {'required': '"Теги" обязательное поле'},
            'cooking_time': {
                'required': '"Время приготовления" обязательное поле',
                'min_value': ('"Время приготовления" не может быть меньше '
                              '1 минуты'),
            },
            'description': {'required': '"Описание" обязательное поле'},
            'image': {'required': '"Картинка" обязательное поле'},
        }

        labels = {
            'title': 'Название рецепта',
            'tags': 'Теги',
            'ingredients': 'Ингредиенты',
            'cooking_time': 'Время приготовления',
            'description': 'Описание',
            'image': 'Загрузить фото',
        }

    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)
        self.fields['ingredients'].required = False

    def clean_ingredients(self):
        data = self.cleaned_data['ingredients']
        all_ingredients = Ingredient.objects.values_list('name', flat=True)

        candidates = [value for key, value in self.data.items()
                      if 'nameIngredient' in key]

        if not candidates:
            raise ValidationError(
                'В рецепт нужно добавить минимум один "Ингредиент"'
            )

        contains_duplicates = any(candidates.count(element) > 1
                                  for element in candidates)

        if contains_duplicates:
            raise ValidationError('"Игредиенты" должны быть уникальными. '
                                  'Повторы запрещены')

        recipe_ingredients = []
        for key, value in self.data.items():

            if self.LOOKUP_NAME in key:
                if value not in all_ingredients:
                    raise ValidationError(
                        f'{value}: Ингредиенты должны быть выбраны из списка')
                ingredient_name = value

            if self.LOOKUP_VALUE in key:
                ingredient_value = value
                if int(ingredient_value) <= 0:
                    raise ValidationError(
                        'Вес/количество ингредиента не может быть меньше 1'
                    )
                recipe_ingredients.append(
                    (Ingredient.objects.get(name=ingredient_name),
                     ingredient_value)
                )

        data = recipe_ingredients
        return data

    def save(self, commit=True):

        recipe = super().save(commit=False)

        if commit:
            recipe.save()
            current_ingredients = recipe.required_ingredients.all()
            current_ingredients.delete()

            ingredients = self.cleaned_data.get('ingredients', [])
            IngredientRecipeMap.objects.bulk_create(
                [
                    IngredientRecipeMap(recipe=recipe, ingredient=ingredient,
                                        quantity=quantity)
                    for ingredient, quantity in ingredients
                ]
            )

        return recipe

apps/recipes/views.py
import operator
from functools import reduce

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Exists, OuterRef, Q
from django.forms import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views import generic

from recipes.forms import RecipeForm
from recipes.models import Favorite, Recipe, Subscribe

User = get_user_model()

ITEMS_PER_PAGE = 6


class ListViewWithFilter(generic.ListView):

    def _get_conditions(self, tags):

        if not tags:
            return Q(tags=None)

        conditions = [
            Q(tags__icontains=value) for key, value in self.TAGS.items()
            if key in tags
        ]

        return reduce(operator.or_, conditions)

    def _update_filter(self):
        change_tag = self.request.GET.get('change_filter')
        self.tags_filter = self._get_filter()

        if change_tag:
            if change_tag in self.tags_filter:
                self.tags_filter.remove(change_tag)
            else:
                self.tags_filter.append(change_tag)

        self.request.session['filter'] = self.tags_filter

        return self.tags_filter

    def _get_filter(self):
        return self.request.session.get('filter', default=self.DEFAULT_FILTER)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.tags_filter
        return context

    TAGS = {tag.name.lower(): tag.value for tag in Recipe.Tag}
    DEFAULT_FILTER = list(TAGS.keys())
    RECIPES_PER_PAGE = ITEMS_PER_PAGE

    paginate_by = RECIPES_PER_PAGE
    template_name = 'index.html'
    context_object_name = 'recipes'


class RecipeListView(ListViewWithFilter):
    def get_queryset(self):
        self.tags_filter = self._update_filter()
        self.condition = self._get_conditions(self.tags_filter)
        queryset = Recipe.objects.filter(self.condition).annotate(
            is_favorite=Exists(Favorite.objects.filter(
                chooser_id=self.request.user.id,
                recipe_id=OuterRef('pk'))
            )
        )
        return queryset


class ProfileListView(ListViewWithFilter):

    def get_queryset(self):
        self.tags_filter = self._update_filter()
        self.condition = self._get_conditions(self.tags_filter)
        self.author = get_object_or_404(User, username=self.kwargs['username'])
        self.author.is_subscribe = Subscribe.objects.filter(
            subscriber_id=self.request.user.id,
            author_id=self.author).exists()

        queryset = self.author.recipes.filter(self.condition).annotate(
            is_favorite=Exists(Favorite.objects.filter(
                chooser_id=self.request.user.id,
                recipe_id=OuterRef('pk'))
            )
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = self.author
        return context


class FavoriteListView(LoginRequiredMixin, ListViewWithFilter):

    def get_queryset(self):
        self.tags_filter = self._update_filter()
        self.condition = self._get_conditions(self.tags_filter)
        queryset = Recipe.objects.filter(
            self.condition,
            favorites__chooser__id=self.request.user.id).annotate(
                is_favorite=Exists(Favorite.objects.filter(
                    chooser_id=self.request.user.id,
                    recipe_id=OuterRef('pk'))
                )
        )
        return queryset


class RecipeDetailView(generic.DetailView):

    template_name = 'recipe_details.html'

    def get_queryset(self):
        queryset = Recipe.objects.annotate(
            is_favorite=Exists(Favorite.objects.filter(
                chooser_id=self.request.user.id,
                recipe_id=OuterRef('pk'))
            )
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recipe = self.get_object()
        is_subscribe = Subscribe.objects.filter(
            subscriber_id=self.request.user.id,
            author=recipe.author).exists()
        context['is_subscribe'] = is_subscribe
        return context


class SubscribeListView(LoginRequiredMixin, generic.ListView):
    paginate_by = ITEMS_PER_PAGE
    template_name = 'subscribes.html'
    context_object_name = 'authors'

    def get_queryset(self):
        return User.objects.filter(
            subscribers__subscriber__id=self.request.user.id).annotate(
                is_subscribe=Exists(Subscribe.objects.filter(
                    subscriber=self.request.user,
                    author_id=OuterRef('pk'))
                )
        )


def page_not_found(request, exception):
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=404
    )


def server_error(request):
    return render(request, 'misc/500.html', status=500)


class RecipeEditView(LoginRequiredMixin, generic.UpdateView):
    model = Recipe
    form_class = RecipeForm
    success_delete_url = reverse_lazy('recipes:index')

    post_url_name = 'new_recipe'
    update_url_name = 'update_recipe'
    delete_url_name = 'delete_recipe'

    delete_template_name = 'recipe_confirm_delete.html'
    form_template_name = 'recipe_form.html'

    def get_url_name(self):
        return self.request.resolver_match.url_name

    def get_template_name(self):
        if self.get_url_name() == self.delete_url_name:
            return self.delete_template_name
        return self.form_template_name

    def get_object(self, queryset=None):
        self.template_name = self.get_template_name()

        try:
            return super().get_object(queryset)
        except AttributeError:
            return None

    def form_valid(self, form):
        if self.get_url_name() == self.post_url_name:
            form.instance.author_id = self.request.user.id
            return super().form_valid(form)

        if self.request.user.is_owner(form.instance):
            return super().form_valid(form)
        form.add_error(None, ValidationError(
            {"Только автор может редактировать рецепт"}))
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.get_url_name() == self.update_url_name:
            context['update'] = True
        return context

    def post(self, request, *args, **kwargs):
        if self.get_url_name() == self.delete_url_name:
            return self.delete(request, *args, **kwargs)
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.request.user.is_owner(self.object):
            return HttpResponseRedirect(self.object.get_absolute_url())
        self.object.delete()
        return HttpResponseRedirect(self.success_delete_url)

apps/shopping_list/views.py
import pdfkit
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic
from recipes.models import IngredientRecipeMap, Recipe
from shopping_list.models import Purchase


class PurchaseMixin():

    def get_shopping_list(self, request):
        if request.user.is_authenticated:
            obj, _ = Purchase.objects.get_or_create(user=request.user)
            return obj.shopping_list
        return request.session.get('shopping_list', default=[])

    def update_shopping_list(self, request, shopping_list):
        if request.user.is_authenticated:
            _ = Purchase.objects.update_or_create(
                user=request.user, defaults={'shopping_list': shopping_list})
        else:
            request.session['shopping_list'] = shopping_list


class ShoppingListView(PurchaseMixin, generic.TemplateView):

    template_name = 'shopping_list/shopping_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        shopping_list = self.get_shopping_list(self.request)
        self.recipes = Recipe.objects.filter(id__in=shopping_list)
        context['recipes'] = self.recipes
        return context


class EmptyShoppingList(generic.TemplateView):
    template_name = 'shopping_list/empty.html'


class DownloadShoppingList(PurchaseMixin, generic.View):

    filename = 'required_ingredients.pdf'
    redirect_url = reverse_lazy('shopping_list:empty')
    template_name = 'shopping_list/download_list.html'
    context_name = 'ingredients'

    def collect_ingredients(self, shopping_list):
        ingredients = IngredientRecipeMap.objects.filter(
            recipe_id__in=shopping_list).values_list(
                'ingredient__name', 'quantity', 'ingredient__units')

        required_ingredients = {}
        for item in ingredients:
            name, quantity, units = item
            key = f'{name} ({units}.)'
            required_ingredients.setdefault(key, 0)
            required_ingredients[key] += quantity

        return required_ingredients

    def generate_pdf(self, data):
        html = render_to_string(self.template_name,
                                {self.context_name: data})

        options = {'enable-local-file-access': None}

        pdf = pdfkit.from_string(html, False, options)

        return pdf

    def get(self, request):
        shopping_list = self.get_shopping_list(request)
        if not shopping_list:
            return redirect(self.redirect_url)

        required_ingredients = self.collect_ingredients(shopping_list)
        pdf = self.generate_pdf(required_ingredients)
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = (f'attachment; '
                                           f'filename="{self.filename}"')
        return response

templates/recipe_details.html
{% extends 'base.html' %}
{% block title %}{{ recipe.title }}{% endblock %}

{% load static %}

{% block stylesheet %}<link rel="stylesheet" href="{% static 'pages/single.css' %}">{% endblock %}

{% block content %}
<div class="single-card" data-id="{{ recipe.id }}" data-author=" {{ recipe.author.id }}">
    <img src="{{ recipe.image.url }}" alt="какой-то текст" class="single-card__image">
    <div class="single-card__info">
        <div class="single-card__header-info">
            <h1 class="single-card__title">{{ recipe.title }}</h1>
            {% if user.is_authenticated %}
            <div class="single-card__favorite">
                <button class="button button_style_none" name="favorites" {% if not recipe.is_favorite %}data-out{% endif %}><span class="icon-favorite icon-favorite_big {% if recipe.is_favorite %}icon-favorite_active{% endif %}"></span></button>
                <div class="single-card__favorite-tooltip tooltip">Добавить в избранное</div>
            </div>
            {% endif %}
        </div>
        <ul class="single-card__items">
            {% if 'обед' in recipe.tags %}
            <li class="single-card__item"><span class="badge badge_style_green">Обед</span></li>
            {% endif %}
            {% if 'завтрак' in recipe.tags %}
            <li class="single-card__item"><span class="badge badge_style_orange">Завтрак</span></li>
            {% endif %}
            {% if 'ужин' in recipe.tags %}
            <li class="single-card__item"><span class="badge badge_style_purple">Ужин</span></li>
            {% endif %}
        </ul>

        <div class="single-card__items single-card__items_column">
            <p class="single-card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
            <ul class="single-card__items">
                <li class="single-card__item"><p class="single-card__text"><span class="icon-user"></span>
                    <a class="single-card__text link" href="{% url 'recipes:profile' recipe.author %}" target="_blank">
                        {% firstof recipe.author.get_full_name recipe.author %}</p></li>
                    </a>
                {% if user == recipe.author %}
                <li class="single-card__item">  <a style="margin-left: 2.5em" href="{% url 'recipes:update_recipe' recipe.id recipe.slug %}" class="single-card__text">Редактировать рецепт</a></li>
                {% endif %}
            </ul>
        </div>
        <ul class="single-card__items">
            {% if recipe.id in shopping_list %}
                <li class="single-card__item"><button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check" button__icon></span> Рецепт добавлен </button></li>
            {% else %}
                <li class="single-card__item"><button class="button button_style_blue" name="purchases" data-out><span class="icon-plus" button__icon></span> Добавить в покупки</button></li>
            {% endif %}
            {% if user.is_authenticated %}
                <li class="single-card__item">
                {% if recipe.author != user %}
                {% if is_subscribe %}
                    <button class="button button_style_light-blue button_size_subscribe" name="subscribe">Отписаться от автора</button>
                {% else %}
                    <button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button>
                {% endif %}
                {% endif %}
                </li>
            {% endif %}
        </ul>
        <div class="single-card__section">
            <h3 class="single-card__section-title">Ингридиенты:</h3>
            <div class="single-card__items single-card__items_column">
                {% for item in recipe.required_ingredients.all %}
                <p class=" single-card__section-item">{{ item }}</p>
                {% endfor %}
            </div>
        </div>
        <div class="single-card__section">
            <h3 class="single-card__section-title">Описание:</h3>
            <p class="single-card__section-text"> {{ recipe.description|linebreaksbr }}</p>
        </div>
        <div class="single-card__section">
            {% with created=recipe.created|date:"G:i, d E Y"  modified=recipe.modified|date:"G:i, d E Y" %}
            <p class="single-card__text" style="color:lightslategray"> создан: {{ created }}</p>
            {% if created != modified %}
            <p class="single-card__text" style="color:lightslategray"> изменен: {{ modified }}</p>
            {% endif %}
            {% endwith %}
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}

    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/config/config.js' %}"></script>

    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/SingleCard.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>

{% if user.is_authenticated %}
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>

    <script src="{% static 'js/foodgram/singlePage.js' %}"></script>
{% else %}
    <script src="{% static 'js/foodgram/singlePageNotAuth.js' %}"></script>
{% endif %}

{% endblock %}

templates/recipe_form.html
{% extends 'base.html' %}
{% block title %}{% if not update %}Создание рецепта{% else %}Редактирование рецепта{% endif %}{% endblock %}
{% load static %}
{% block stylesheet %}<link rel="stylesheet" href="{% static '/pages/form.css' %}">{% endblock %}

{% block header %}{% if not update %}Создание рецепта{% else %}Редактирование рецепта{% endif %}{% endblock %}

{% block content %}

<div class="form-container">
    <form class="form" method="post" enctype="multipart/form-data">{% csrf_token %}
        {% with form.title as field %}
        <div class="form__group">
            <label for="{{ field.id_for_label }}" class="form__label"> {{ field.label }}</label>
            <div class="form__field-group">
                <input type="text" id="{{ field.id_for_label }}" name="{{ field.name }}" class="form__input" {% if field.value %}value="{{ field.value }}"{% endif %}>
                <span class="form__error">{% if form.title.errors %} {{ form.title.errors|escape }} {% endif %}</span>
            </div>
        </div>
        {% endwith %}
        <!-- Tags field -->
        <div class="form__group">
            <p class="form__label">{{ form.tags.label }}</p>
            <div class="form__field-group">
                <div class="tags">
                    {% for value, label in form.tags.field.choices %}
                    <div class="tags__item">
                        <input type="checkbox" name="{{ form.tags.name }}" id="id_{{value}}" class="tags__checkbox tags__checkbox_style_{% cycle 'orange' 'green' 'purple' %}" value="{{ value }}" {% if value in form.tags.value %}checked{% endif %}>
                        <label for="id_{{value}}" class="tags__label">{{ label|title }}</label>
                    </div>
                    {% endfor %}

                </div>
                <span class="form__error">{% if form.tags.errors %} {{ form.tags.errors|escape }} {% endif %}</span>
            </div>
        </div>

        <!-- Ingredients field -->
        <div class="form__group">
            <label for="nameIngredient" class="form__label"> {{ form.ingredients.label }}</label>
            <div class="form__field-group">
                <div class="form__field-group-ingredientes">
                    <div class="form__dropdown">
                        <input type="text" id="nameIngredient" class="form__input">
                        <div class="form__dropdown-items"></div>
                    </div>
                    <input type="number" id="cantidad" class="form__input" min="1">
                    <label for="cantidad" class="form__label" id="cantidadVal"></label>
                </div>
                <div class="form__field-group-ingredientes-container">
                    {% for ingredient in form.instance.required_ingredients.all %}
                    <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}">
                        <span> {{ ingredient|lower }}</span>
                        <span class="form__field-item-delete"></span>
                        <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.ingredient.name }}">
                        <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.quantity }}">
                        <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.ingredient.units }}">
                    </div>
                    {% endfor %}
                </div>
                <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                <span class="form__error">{% if form.ingredients.errors %} {{ form.ingredients.errors|escape }} {% endif %}</span>
            </div>
        </div>
        <!-- Cooking_time -->
        {% with form.cooking_time as field %}
        <div class="form__group">
            <label for="{{ field.id_for_label }}" class="form__label">{{ field.label }}</label>
            <div class="form__field-group form__field-group_time">
                <input type="text" id="{{ field.id_for_label }}" name="{{ field.name }}" class="form__input" {% if field.value %}value="{{ field.value }}"{% endif %}>
                <label for="{{ field.id_for_label }}" class="form__label">минут</label>
                <span class="form__error">{% if field.errors%} {{ field.errors|escape }} {% endif %}</span>
            </div>
        </div>
        {% endwith %}

        {% with form.description as field %}
        <div class="form__group">
            <label for="{{ field.id_for_label }}" class="form__label">{{ field.label }}</label>
            <div class="form__field-group">
                <textarea name="{{ field.name }}" id="{{ field.id_for_label }}" rows="8" class="form__textarea">{% if field.value %}{{ field.value }}{% endif %}</textarea>
                <span class="form__error">{% if field.errors %} {{ field.errors|escape }} {% endif %}</span>
            </div>
        </div>
        {% endwith %}

        {% with form.image as field %}
        <div class="form__group">
            <span class="form__label">{{ field.label }}</span>
            <div class="form__field-group">
                <input type="file" name="{{ field.name }}" id="{{ field.id_for_label }}">
                {% if update %}
                <a href="{{ form.instance.image.url }}">Текущий файл: {{ form.instance.image.name }}</a>
                {% endif %}
                <span class="form__error">{% if field.errors %} {{ field.errors|escape }} {% endif %}</span>
            </div>
        </div>
        {% endwith %}
        <div class="form__footer">
            {% if not update %}
                <button class="button button_style_blue">Создать рецепт</button>
            {% else %}
                <button class="button button_style_blue">Сохранить</button> <a style="margin-left: 2.5em" href="{% url 'recipes:delete_recipe' form.instance.id form.instance.slug %}" class="form__ingredient-link">Удалить</a>
            {% endif %}
        </div>
    </form>
</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/foodgram/formRecipe.js' %}"></script>
{% endblock %}

templates/subscribes.html
{% extends 'base.html' %}
{% block title %}Мои подписки{% endblock %}
{% load static %}
{% block stylesheet %}<link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">{% endblock %}

{% block header %}Мои подписки{% endblock %}

{% block content %}
{% load correct_recipe_case %}
<div class="card-list">
    {% for author in authors %}
    <div class="card-user" data-author="{{ author.id }}">
        <div class="card-user__header">
            <h2 class="card-user__title">
                <a class="card-user__title link" href="{% url 'recipes:profile' author %}" target="_blank">
                {% firstof author.get_full_name author %}
                </a>
            </h2>
        </div>
        <div class="card-user__body">
            <ul class="card-user__items">
                {% for recipe in author.recipes.all|slice:":3" %}
                <li class="card-user__item">
                    <div class="recipe">
                        <img src="{{ recipe.image.url }}" alt="какой-то-текст" class="recipe__image">
                        <a class="recipe__title link" href="{{ recipe.get_absolute_url }}" target="_blank"> {{ recipe.title }}</a>
                        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
                    </div>
                </li>
                {% endfor %}

                {% with author.recipes.count as count %}
                {% if count > 3 %}
                <li class="card-user__item">
                    <a href="{% url 'recipes:profile' author %}" class="card-user__link link">Еще {{ count|add:-3|recipe_case }} ...</a>
                </li>
                {% endif %}
                {% endwith %}
            </ul>
        </div>
        <div class="card-user__footer">
          {% if author.is_subscribe %}
            <button class="button button_style_light-blue button_size_subscribe" name="subscribe">Отписаться от автора</button>
          {% else %}
            <button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button>
          {% endif %}
        </div>
    </div>
    {% empty %}
        <div class="card-user__title">Вы не подпсаны ни на одного автора</div>
    {% endfor %}
</div>

{% endblock %}

{% block pagination %}
    {% if authors %}
        {% include 'elements/paginator.html' %}
    {% endif %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/MyFollow.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/foodgram/myFollow.js' %}"></script>
{% endblock %}