apps/shopping_list/urls.py
from django.urls import path
from shopping_list import views


app_name = 'shopping_list'

urlpatterns = [
    path('', views.ShoppingListView.as_view(), name='main'),
    path('download/', views.DownloadShoppingList.as_view(), name='download'),
    path('download/empty', views.EmptyShoppingList.as_view(), name='empty')
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500


admin.site.site_header = "Foodgram Admin"
admin.site.site_title = "Foodgram Admin Panel"
admin.site.index_title = "Welcome to Foodgram"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('about/', include('about.urls', namespace='about')),
    path('shopping_list/', include('shopping_list.urls',
         namespace='shopping_list')),
    path('', include('recipes.urls', namespace='recipes')),
]

handler404 = "recipes.views.page_not_found"  # noqa
handler500 = "recipes.views.server_error"  # noqa

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

apps/shopping_list/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Purchase(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                related_name='carts',
                                verbose_name='Пользователь')

    shopping_list = models.JSONField(verbose_name='Список рецептов',
                                     default=list)

    class Meta:
        verbose_name = 'Список покупок'
        verbose_name_plural = 'Списки покупок'

    def __str__(self):
        return f'Список покупок {self.user}'

apps/shopping_list/views.py
import pdfkit
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic
from recipes.models import IngredientRecipeMap, Recipe
from shopping_list.models import Purchase


class PurchaseMixin():

    def get_shopping_list(self, request):
        if request.user.is_authenticated:
            obj, _ = Purchase.objects.get_or_create(user=request.user)
            return obj.shopping_list
        return request.session.get('shopping_list', default=[])

    def update_shopping_list(self, request, shopping_list):
        if request.user.is_authenticated:
            _ = Purchase.objects.update_or_create(
                user=request.user, defaults={'shopping_list': shopping_list})
        else:
            request.session['shopping_list'] = shopping_list


class ShoppingListView(PurchaseMixin, generic.TemplateView):

    template_name = 'shopping_list/shopping_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        shopping_list = self.get_shopping_list(self.request)
        self.recipes = Recipe.objects.filter(id__in=shopping_list)
        context['recipes'] = self.recipes
        return context


class EmptyShoppingList(generic.TemplateView):
    template_name = 'shopping_list/empty.html'


class DownloadShoppingList(PurchaseMixin, generic.View):

    filename = 'required_ingredients.pdf'
    redirect_url = reverse_lazy('shopping_list:empty')
    template_name = 'shopping_list/download_list.html'
    context_name = 'ingredients'

    def collect_ingredients(self, shopping_list):
        ingredients = IngredientRecipeMap.objects.filter(
            recipe_id__in=shopping_list).values_list(
                'ingredient__name', 'quantity', 'ingredient__units')

        required_ingredients = {}
        for item in ingredients:
            name, quantity, units = item
            key = f'{name} ({units}.)'
            required_ingredients.setdefault(key, 0)
            required_ingredients[key] += quantity

        return required_ingredients

    def generate_pdf(self, data):
        html = render_to_string(self.template_name,
                                {self.context_name: data})

        options = {'enable-local-file-access': None}

        pdf = pdfkit.from_string(html, False, options)

        return pdf

    def get(self, request):
        shopping_list = self.get_shopping_list(request)
        if not shopping_list:
            return redirect(self.redirect_url)

        required_ingredients = self.collect_ingredients(shopping_list)
        pdf = self.generate_pdf(required_ingredients)
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = (f'attachment; '
                                           f'filename="{self.filename}"')
        return response

templates/shopping_list/download_list.html
<base href="/Users/morf/Dev/course5_Diploma/foodgram-project/" target="_blank" />
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{{ STATIC_URL }}pages/shopList.css">
</head>

<body class="body">
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Список покупок</h1>
            <h2 class="main__title">Для приготовления выбранных блюд вам понадобится:</h2>
            {% for ingredient, qunatity in ingredients.items %}
                <p>{{ingredient}} - {{qunatity}}</p>
            {% endfor %}
        </div>
    </main>
</body>
</html>

templates/shopping_list/empty.html
{% extends 'base.html' %}

{% block title %}Список покупок{% endblock %}

{% load static %}



{% block stylesheet %}<link rel="stylesheet" href="{% static 'pages/index.css' %}">{% endblock %}

{% block header %}Список покупок пуст{% endblock %}

{% block content %}
    <div class="custom-center-block">
        <p class="custom-text-block">Вы не добавли ни одного рецепта в список покупок</p>
    </div>
{% endblock %}

templates/shopping_list/shopping_list.html
{% extends 'base.html' %}
{% block title %}Список покупок{% endblock %}
{% load static %}
{% block stylesheet %}<link rel="stylesheet" href="{% static 'pages/shopList.css' %}">{% endblock %}

{% block header %}Список покупок{% endblock %}

{% block content %}
<div class="card-list card-list_column">
    <ul class="shopping-list">
        {% for recipe in recipes %}
        <li class="shopping-list__item" data-id="{{ recipe.id }}">
            <div class="recipe recipe_reverse">
                <a href="{{ recipe.get_absolute_url }}" class="link" target="_blank"><img src="{{ recipe.image.url }}" alt="какой-то текст" class="recipe__image recipe__image_big"></a>
                <a href="{{ recipe.get_absolute_url }}" class="link" target="_blank"><h3 class="recipe__title">{{ recipe.title }}</h3></a>
                <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
            </div>
            <a href="#" class="shopping-list__button link">Удалить</a>
        </li>
        {% empty %}
            <h3 class="recipe__title">Вы не добавили ни одного рецепта в список покупок</h3>
        {% endfor %}
    </ul>
    {% if recipes %}
        <a href="{% url 'shopping_list:download' %}"><button class="button button_style_blue" id='download_button'>Скачать список</button></a>
    {% endif %}

</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/components/ShopList.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/foodgram/shopList.js' %}"></script>
{% endblock %}